// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQMbHF9K0AmIbuauUEegq6U2zDMofdFwU',
    appId: '1:559550639683:web:71aea5149ccabd5574eef6',
    messagingSenderId: '559550639683',
    projectId: 'quicktask-a7b47',
    authDomain: 'quicktask-a7b47.firebaseapp.com',
    storageBucket: 'quicktask-a7b47.firebasestorage.app',
    measurementId: 'G-0LEVCVF8RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJJJCbo1yBQ2HB_iJyLEJf9Qx3HqN2qo',
    appId: '1:559550639683:android:ab166be89349d0d074eef6',
    messagingSenderId: '559550639683',
    projectId: 'quicktask-a7b47',
    storageBucket: 'quicktask-a7b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_bec2FvCHeIQIs5e6umoKIW9sKZWVs4M',
    appId: '1:559550639683:ios:e177248e228b974974eef6',
    messagingSenderId: '559550639683',
    projectId: 'quicktask-a7b47',
    storageBucket: 'quicktask-a7b47.firebasestorage.app',
    androidClientId: '559550639683-4ob7fesehv8m0efp7830ormsbparhekl.apps.googleusercontent.com',
    iosClientId: '559550639683-bjm07ettk0nglqnpttgfj254hlrnd694.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicktask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_bec2FvCHeIQIs5e6umoKIW9sKZWVs4M',
    appId: '1:559550639683:ios:e177248e228b974974eef6',
    messagingSenderId: '559550639683',
    projectId: 'quicktask-a7b47',
    storageBucket: 'quicktask-a7b47.firebasestorage.app',
    androidClientId: '559550639683-4ob7fesehv8m0efp7830ormsbparhekl.apps.googleusercontent.com',
    iosClientId: '559550639683-bjm07ettk0nglqnpttgfj254hlrnd694.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicktask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQMbHF9K0AmIbuauUEegq6U2zDMofdFwU',
    appId: '1:559550639683:web:9589c78a7835087574eef6',
    messagingSenderId: '559550639683',
    projectId: 'quicktask-a7b47',
    authDomain: 'quicktask-a7b47.firebaseapp.com',
    storageBucket: 'quicktask-a7b47.firebasestorage.app',
    measurementId: 'G-W7J2QPVH1W',
  );
}
